version: '2'
services:
  postgres:
    image: postgres:11.0-alpine
    user: postgres:postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /postgres-docker:/var/lib/postgresql/data
      - /tmp:/tmp
  adminer:
    image: adminer
    restart: always